### ISSUE TITLE
Remove version from Kafka agent

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#118]
Currently, in the Kafka images, we have a `STRIMZI_VERSION` env var which is mainly used for running the related Kafka agent version in the `kafka_run_sh` script.
Btw the image descriptor doesn't use this env var for naming the Kafka agent in the `artifacts` section where the version is hardcoded.
It's not great to deal with it and having this two in sync.
I guess we can just delete the env var and drop the version from the kafka agent artifact.
Is there any hurt I cannot see in doing that? @kyguy

**Comment by scholzj** [comment]
Should this be done upstream?

**Comment by ppatierno** [comment]
Well, upstream all the Strimzi related artifacts (CO, TO, kafka-agent, ...) has the strimzi version as suffix. Here we don't need that because artifacts are identified by MD5 from PNC builds so we don't have strimzi version in the CO, TO ... archive/jar files. For this reason I was thinking why we have that just for the kafka agent.

**Comment by scholzj** [comment]
Ok, thanks for the explanation.

**Comment by kyguy** [comment]
The kafka_run.sh script we backport from upstream uses a `STRIMZI_VERSION` env var here [1]. To remove the `STRIMZI_VERSION` we would need to either:

1.Label the kafka-agent jar to `kafka-agent-.jar` verbatim here. [2]
2.Swap `${STIMZI_VERSION}` with a wildcard `*` in this script [1] when we backport.
3.Swap `${STIMZI_VERSION}` with a wildcard `*` in this script [3] upstream.

[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/2840b57a09c5a35c6714ca3ad150919682c8816a/kafka/modules/kafka/scripts/kafka_run.sh#L26
[2] https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/2840b57a09c5a35c6714ca3ad150919682c8816a/kafka/kafka-2.1.1/image.yaml#L61
[3] https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/scripts/kafka_run.sh#L26

**Comment by ppatierno** [comment]
I remember now! We tried to remove it and then it turned out that we needed to change the `kafka_run.sh` script content when backporting from upstream. We agreed that it's always better to not touch scripts when backporting otherwise things become complicated. At this point we should come back to @scholzj idea to remove that from upstream.

**Comment by kyguy** [comment]
The first option could work too, in case we don't want to change upstream:
> 1.Label the kafka-agent jar to kafka-agent-.jar verbatim here. [2]
TBH I didn't think of it before until you brought it up but I think it might be a simpler change.  When a bash env var value is not provided but referenced in scripts, it results in an empty string at runtime. So if we remove `STIMZI_VERSION` env var from the image descriptor file,  the `kafka-agent-${STRIMZI_VERSION}.jar` in kafka_run.sh [1] will become `kafka-agent-`.

By default, all the artifacts in the image descriptor file will be renamed to the `name` we provide in the artifact section. So if we change, `name: kafka-agent-0.12.0.jar` to `name: kafka-agent-.jar ` and remove the `STRIMZI_VERSION` env var in the image descriptor, we should be all set

[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/2840b57a09c5a35c6714ca3ad150919682c8816a/kafka/modules/kafka/scripts/kafka_run.sh#L26
[2] https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/2840b57a09c5a35c6714ca3ad150919682c8816a/kafka/kafka-2.1.1/image.yaml#L61

**Comment by ppatierno** [comment]
Well ending the Kafka agent name with a dash is not great naming, I would avoid it.
Maybe we can try to remove it upstream. Tbh it's the only component to have the version, all operators and even the JMX exporter doesn't have it.

**Comment by kyguy** [comment]
Yea you are right, upstream change sounds good to me +1

**Comment by ppatierno** [comment]
There is a Strimzi upstream PR for this https://github.com/strimzi/strimzi-kafka-operator/pull/1874
