### ISSUE TITLE
Possibility of updating "pullspecs"

### ISSUE THREAD

**Issue by kyguy** [jboss-container-images/amqstreams-1-openshift-image#181]
OSBS team is requesting we update env vars in our manifest files that specify multiple images/values to just specify one. This is to fall inline with their automation efforts with SHA digests. For example:
``` 
 - name: STRIMZI_KAFKA_IMAGES
   value: |
     2.0.0=registry.access.redhat.com/amq7/amq-streams-kafka:1.1.0-kafka-2.0.0
     2.1.1=registry.access.redhat.com/amq7/amq-streams-kafka:1.1.0-kafka-2.1.1
```
I know this format is used to support upgrades for AMQ Streams, so this issue is to discuss the feasibility/possibility of this being changed or if we should push back on the requirement. If it is possible, what should the format look like?

**Comment by kyguy** [comment]
As discussed offline, these changes would not be worth the incurred overhead. Looking into alternatives, for instance, using annotations to hold pull.specs for OSBS [1]. OSBS would retrieve the pull.specs from the annotations and replace all of the equivalent pull.specs listed in the CSV file with the SHA digests. The only issue it that the type of SHAs digests that are swapped in are manifest digest lists which are not supported by the OpenSHift internal registry and will break our S2I feature. We need **platform specific digests**

[1] https://osbs.readthedocs.io/en/latest/users.html#pullspec-locations

**Comment by k-wall** [comment]
@kyguy is this issue still relevant?

**Comment by kyguy** [comment]
Closing as this is no longer relevant, all issues have been fixed by internal services
