### ISSUE TITLE
Moving bridge image to Java 11 as runtime

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#217]
As per #216 about Kafka and operator images, even the bridge image has to be moved to use Java 11 as runtime when the corresponding upstream issue https://github.com/strimzi/strimzi-kafka-bridge/issues/446 will be closed.

**Comment by kyguy** [comment]
Resolved as part of https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/237
