### ISSUE TITLE
Change metadata image to be built from "scratch"

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#226]
The operator metadata image should be built FROM "scratch" but this kind of build is not supported by the current cekit version.
When this work https://github.com/cekit/cekit/pull/652 will be done and new cekit version release we can make the change.

**Comment by kyguy** [comment]
Resolved with https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/232, closing issue
