### ISSUE TITLE
Moving to bundle format using cekit 3.7.0 for the build

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#229]
Now that cekit 3.7.0 is released with support for build from SCRATCH, we should finally remove ALL the old CSVs for the 1.6.0 version and leaving only the CSV for 1.6.0 in order to build the new operator metadata (directly in the bundle format) with the new cekit.

**Comment by kyguy** [comment]
Resolved with https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/232, closing issue.

Cherry-picked for 16-dev branch
