### ISSUE TITLE
Adding JVM tools and other basic debug tools to images

### ISSUE THREAD

**Issue by kyguy** [jboss-container-images/amqstreams-1-openshift-image#236]
Received a request to add the following RPMs to the AMQ Streams images:

```
java-1.8.0-openjdk-devel-debug (rhel-7-server-optional-rpms)
net-tools
lsof
```
for the following tools:

``` jstack, jcmd, jmap, netstat, lsof```

We can add these packages as part of next release

**Comment by kyguy** [comment]
Replace `java-1.8.0-openjdk-devel-debug` with java-1.8.0-openjdk-devel

**Comment by ppatierno** [comment]
see #216 and #217 for 1.6 they are related to this

**Comment by kyguy** [comment]
Resolved as part of https://github.com/jboss-container-images/amqstreams-1-openshift-image/pull/237
