### ISSUE TITLE
Moving from Java devel to headless

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#253]
The upstream images install the "headless" version of the Java OpenJDK while downstream we are using the "devel" with more stuff. Is it really needed? @kyguy do you remember a good reason why we are using it? For running we need the runtime not developer tools in it, or is it for some debugging stuff on the images?

**Comment by kyguy** [comment]
You are exactly right, we had a request for some specific debugging tools, e.g. ` jstack, jcmd, jmap` [1] and this was the smallest RPM that provided them

[1] https://github.com/jboss-container-images/amqstreams-1-openshift-image/issues/236

**Comment by ppatierno** [comment]
ok thanks!
