### ISSUE TITLE
Inconsistency s390x support declaration across modules and image descriptors

### ISSUE THREAD

**Issue by ppatierno** [jboss-container-images/amqstreams-1-openshift-image#344]
@kyguy while adding the s390x support to AMQ Streams 2.1 with #343 as it was done for 2.0 with #336 I noticed some missing or redundancy about `content_sets` declaration.

* the `kafka/modules/kafka/base/module.yaml` contains content sets for x86_64 and ppc64le but it's missing the s390x. I assume it works anyway because we have the s390x declaration in both the Kafka related images `kafka/kafka-3.0.0/image.yaml` and `kafka/kafka-3.1.0/image.yaml`. I noticed that the base module install some packages which are common across the two Kafka versions but it should have the s390x content set for consistency or maybe removing the others as well. The build should work anyway because cekit should use the content sets declared in the image descriptors for both Kafka which contains all of them (x86_64, ppc64le, s390x). So my question is, do we really need the content sets declaration in the base module? 
* the same comment as above is valid comparing the operator module `operator/modules/operator/module.yaml` which is missing the s390x in the content sets and the operator image descriptor `operator/image.yaml` which contains all of the platform for packeges repo. 
* again the same for bridge and drain cleaner. The modules are missing s390x but image descriptors contain it. For bridge `bridge/modules/bridge/module.yaml` vs `bridge/image.yaml` and for drain cleaner `drain-cleaner/modules/drain-cleaner/module.yaml` vs `drain-cleaner/image.yaml`.

**Comment by kyguy** [comment]
> do we really need the content sets declaration in the base module?

We don't, this was an oversight on my part. RPM and content_set declarations in the module files are ignored by Cekit and can be removed from all of our module files!

**Comment by ppatierno** [comment]
> RPM and content_set declarations in the module files are ignored by Cekit

wait ... I would agree on the fact that content_set declaration in the module file is ignored by Cekit and can be removed but are we sure about the `packages.install` section listing rpms to install?
I am saying that because for example, the `kafka/modules/kafka/base/module.yaml` has the following:

```yaml
install:
    - unzip
    - tar
    - rsync
    - shadow-utils # groupadd
    - gzip
    - kafka_exporter
```

while the `kafka/kafka-3.1.0/image.yaml` has:

```yaml
install:
    - java-11-openjdk-devel
    - gettext
    - nmap-ncat
    - openssl
    - hostname
    - stunnel
    - net-tools
    - bind-utils
    - tini
    - lsof
```

There is no overlapping or duplication so I would assume that RPMs listed in the base module are actually installed, or?
