### ISSUE TITLE
Make Kafka run on Java 17

### ISSUE THREAD

**Issue by andconstantinescu** [jboss-container-images/amqstreams-1-openshift-image#386]
Hello,

Since Java 11 will be at the end of its support in September 2023, would it be possible already get an upgrade to Java 17? 

I'm asking because we're currently experiencing issues running Java 17 built connector jars in a connect cluster. We also couldn't find any workaround to that, so we had to downgrade back to Java 11.

Thanks!

**Comment by ppatierno** [comment]
Having Java 17 is already planned for AMQ Streams 2.4.0 (in April).

**Comment by andconstantinescu** [comment]
Thanks a lot for the info. Will wait for the 2.4.0 then.
