### ISSUE TITLE
Update image reference before AMQ Streams 2.7 release is made.

### ISSUE THREAD

**Issue by k-wall** [jboss-container-images/amqstreams-1-openshift-image#454]
https://github.com/jboss-container-images/amqstreams-1-openshift-image/blob/3012ef37177ddc67c4cdd66608c22decd1b0b220/examples/proxy/record-encryption/base/proxy/proxy-deployment.yaml#L20

**Comment by k-wall** [comment]
This issue was done.  It should be closed.

**Comment by k-wall** [comment]
@OwenCorrigan76 could you review and mark as closed?

**Comment by OwenCorrigan76** [comment]
Closing
