### ISSUE TITLE
Move chain automation tool into separate repository

### ISSUE THREAD

**Issue by kyguy** [jboss-container-images/amqstreams-1-openshift-image#90]
Maintaining the tool in this repository is becoming cumbersome due to the number distinct branches and pollutes the history of the image script changes. The tool will also become obsolete with the changes coming with 1.2.0 release.

We should separate the tool into its own repo and package it up properly when its worth it and we have time.

**Comment by ppatierno** [comment]
@kyguy you removed the automation tool, is it moved to a separate repo? Can we close this one?

**Comment by kyguy** [comment]
Yes, just moved it to a separate repo for now https://github.com/kyguy/chain
